Feature: IssueTests
	Managing issues with an authorised client


Scenario: An authenticated client can create an issue
	Given authenticated client is set for a create issue request
	When I send a post request with the following request body
	| name   | value                              |
	| title  | Hi                                 |
	| body   | Thus issue was menerated by a test |
	| labels | bug                                |
	Then success response status should be 201
	And  response body contains issue information


Scenario: An authenticated client can edit an issue
	Given authenticated client is set for an edit issue 1 request
	When I send a patch request with the following request body
	| name   | value                              |
	| title  | Hello                              |
	| body   | This issue was generated by a test |
	| labels | bug,Document                       |
	Then success response status should be 200
	And  response body contains issue information 



Scenario: An authenticated client can list issues for a repo
	Given authenticated client is set for a retrieve repo issues request
	And the first issue created has title Hello
	When I send the get request
	Then success response status should be 200
	And  response body contains a list of issues with recently updated issue 1 appearing last